# Generated by Django 3.1.2 on 2020-12-07 21:40

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('org_name', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('size', models.CharField(choices=[(1, 'BG'), (2, 'MC'), (3, 'MD'), (4, 'ST')], max_length=2)),
                ('sector', models.CharField(choices=[(1, 'DM'), (2, 'GD'), (3, 'MA'), (4, 'PT'), (5, 'VA')], max_length=2)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('emp_job_title', models.CharField(max_length=50, verbose_name='Employee Job Title')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruiters.organization', verbose_name='Organization Name')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
