# Generated by Django 3.1.2 on 2020-12-08 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('size', models.IntegerField(choices=[(1, 'BG'), (2, 'MC'), (3, 'MD'), (4, 'ST')])),
                ('sector', models.IntegerField(choices=[(1, 'DM'), (2, 'GD'), (3, 'MA'), (4, 'PT'), (5, 'VA')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_job_title', models.CharField(max_length=50, verbose_name='Employee Job Title')),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruiters.organization', verbose_name='Organization Name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
