# Generated by Django 3.1.2 on 2020-12-09 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_length', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_job_title', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('salary_upper', models.DecimalField(decimal_places=2, max_digits=8)),
                ('salary_lower', models.DecimalField(decimal_places=2, max_digits=8)),
                ('relocation_assistance', models.BooleanField(verbose_name='Relocation Assistance Available?')),
                ('contract_length', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seekers.contractlength')),
                ('contract_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seekers.contracttype')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recruiters.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_resume', models.BooleanField()),
                ('phone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('is_seeker', 'Is a Job Seeker')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_job_title', models.CharField(max_length=50)),
                ('is_accepted', models.BooleanField()),
                ('extended_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recruiters.recruiter')),
                ('extended_to', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='seekers.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekers.listing'),
        ),
        migrations.AddField(
            model_name='application',
            name='seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekers.seeker'),
        ),
        migrations.CreateModel(
            name='SeekerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced'), ('4', 'Expert')], max_length=1)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekers.seeker')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekers.skill')),
            ],
            options={
                'unique_together': {('seeker', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='ListingSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced'), ('4', 'Expert')], max_length=1)),
                ('is_required', models.BooleanField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekers.listing')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekers.skill')),
            ],
            options={
                'unique_together': {('skill', 'listing')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('seeker', 'listing')},
        ),
    ]
