# Generated by Django 3.1.2 on 2020-12-08 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seekers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('seeker', 'listing')},
        ),
    ]
