# Generated by Django 3.1.2 on 2020-12-09 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
        ('seekers', '0002_auto_20201208_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='resume',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recruiters.recruiter'),
        ),
        migrations.AlterField(
            model_name='listingskill',
            name='level',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced'), ('4', 'Expert')], max_length=1),
        ),
        migrations.AlterField(
            model_name='listingskill',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekers.listing'),
        ),
        migrations.AlterField(
            model_name='listingskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekers.skill'),
        ),
        migrations.AlterField(
            model_name='seekerskill',
            name='level',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced'), ('4', 'Expert')], max_length=1),
        ),
        migrations.AlterField(
            model_name='seekerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seekers.skill'),
        ),
    ]
